### ISSUE TITLE
USER STORY: <Double-Booking>

### ISSUE THREAD

**Issue by BjornRodin** [BjornRodin/book-a-contractor#17]
As a **Site User** I can **not book several sessions during the same date** so that **can't double-book myself if I already have a booking that day.**

# Acceptance Criteria

* Acceptance Criteria 1: Not being able to book another session the same date as i've previously booked.
* Acceptance Criteria 2: Only people logged in can view and submit the booking form.

# Tasks
- [x] Add authentication if-else statements in booking_form.html to make sure you can see the form only when logged in.
- [x] If not logged in, information is provided for the user and a button redirecting to login page.
- [x] Check the database if there already is a booking for the user at the date they are trying to book, if there isnt one then the submisson will succeed.

**Comment by BjornRodin** [comment]
I changed this when i realized it would be better to avoid doublebookings for anyone. So instead of not being able to book the same day for the user the limitations now is that a booking can only be made at a date and time where there is no other bookings.
